version: '3.8'

services:
  builder:
    image: ghcr.io/d3fau4/nx-dev:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/bash -c "bash ./exlaunch.sh build && cp -r deploy /workspace/deploy_output"

volumes:
  workspace:
